#Put Necessary Libraries Here
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggthemes)
library(plotly)
library(ggplot2)
library(tidyverse)
library(modelr)
library(broom)
library(glmnet)
library(kableExtra)
library(scales)

game = read.csv("nhl-game-data/game.csv") %>% select(game_id, season, type, date_time, away_team_id, home_team_id, away_goals, home_goals, venue_time_zone_tz) %>% filter(type == 'R') %>% rename('away_goals_final' = 'away_goals', 'home_goals_final' = 'home_goals')
goalie_stats = read.csv("nhl-game-data/game_goalie_stats.csv")
plays = read.csv("nhl-game-data/game_plays.csv")
plays_players = read.csv("nhl-game-data/game_plays_players.csv")
shifts = read.csv("nhl-game-data/game_shifts.csv")
skater_stats = read.csv("nhl-game-data/game_skater_stats.csv")
teams_stats = read.csv("nhl-game-data/game_teams_stats.csv")
player_info = read.csv("nhl-game-data/player_info.csv") %>% select(player_id, firstName, lastName, primaryPosition)
team_info = read.csv("nhl-game-data/team_info.csv") %>% select(team_id, franchiseId, shortName, teamName)

game_team_stats = right_join(game, teams_stats) %>% right_join(team_info) %>% right_join(plays) %>% filter(type == 'R')
write.csv(game_team_stats, file = "nhl-game-data/game_outcomes.csv")
